# Generated by Django 5.2.3 on 2025-06-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('num_tel', models.CharField(blank=True, max_length=15)),
                ('image_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
